
Row
-----------------------------------------------------------------------

### Total number of repositories

```{r, eval=TRUE}
flexdashboard::valueBox(
   value = formattable::comma(
      x = dplyr::n_distinct(languages[["repo_name"]]),
      digits = integer_precision
   ),
   icon = github_icon,
   color = "info"
)
```

### Private

```{r, eval=TRUE}
private_repos <- languages %>% 
   dplyr::group_by(
      is_private
   ) %>% 
   dplyr::summarise(
      repos = dplyr::n_distinct(repo_name, na.rm = TRUE),
      .groups = "drop_last"
   ) %>% 
   dplyr::mutate(
      prop = repos / base::sum(repos, na.rm = TRUE)
   )
flexdashboard::valueBox(
   value = formattable::percent(
      x = private_repos[private_repos[["is_private"]], ][["prop"]] %|||% 0,
      digits = percentage_precision
   ),
   icon = private_repo_icon,
   color = "info"
)
```

### Archived

```{r, eval=TRUE}
archived_repos <- languages %>% 
   dplyr::group_by(
      is_archived
   ) %>% 
   dplyr::summarise(
      repos = dplyr::n_distinct(repo_name, na.rm = TRUE),
      .groups = "drop_last"
   ) %>% 
   dplyr::mutate(
      prop = repos / base::sum(repos, na.rm = TRUE)
   )
flexdashboard::valueBox(
   value = formattable::percent(
      x = archived_repos[archived_repos[["is_archived"]], ][["prop"]] %|||% 0,
      digits = percentage_precision
   ),
   icon = archived_repo_icon,
   color = "info"
)
```

### Total number of languges

```{r, eval=TRUE}
flexdashboard::valueBox(
   value = formattable::comma(
      x = dplyr::n_distinct(languages[["language"]]),
      digits = integer_precision
   ),
   icon = "fa-code",
   color = "info"
)
```

Row
-----------------------------------------------------------------------

```{r}
lang_data <- languages %>%
   dplyr::group_by(
      language
   ) %>%
   dplyr::summarise(
      size = base::sum(size, na.rm = TRUE),
      repos = dplyr::n_distinct(repo_name, na.rm = TRUE),
      .groups = "drop"
   ) %>%
   dplyr::transmute(
      language,
      size,
      prop_size = size / base::sum(size, na.rm = TRUE),
      repos,
      prop_repos = repos / dplyr::n_distinct(languages[["repo_name"]], na.rm = TRUE),
   )
```

### Language use (byte size)

```{r, eval=TRUE}
lang_data %>%
   dplyr::mutate(
      language = forcats::as_factor(language),
      language = forcats::fct_reorder(
         .f = language,
         .x = prop_size
      )
   ) %>%
   plotly::plot_ly() %>%
   plotly::add_trace(
      x = ~prop_size,
      y = ~language,
      type = "bar",
      color = ~language,
      colors = colors_vct,
      hovertemplate = ~base::paste0(
         base::paste0("<b>", language, "</b>"),
         "<br>",
         "<b>Share:</b> ",
         formattable::percent(
            x = prop_size,
            digits = 2L
         ),
         "<br>",
         base::paste0(
            "Used in ",
            repos,
            " of ",
            dplyr::n_distinct(languages[["repo_name"]], na.rm = TRUE),
            " repos (",
            formattable::percent(
               x = repos / dplyr::n_distinct(languages[["repo_name"]], na.rm = TRUE),
               digits = 2L
            ),
            ")"
         ),
         "<extra></extra>"
      )
   ) %>%
   plotly::layout(
      xaxis = base::list(
         title = NA,
         tickformat = "%"
      ),
      yaxis = base::list(
         title = NA
      ),
      paper_bgcolor = "#f5f5f5",
      plot_bgcolor = "#f5f5f5"
   ) %>%
   plotly::config(
      displayModeBar = FALSE
   )
```

Row
-----------------------------------------------------------------------

### Language use (repos usage)

```{r, eval=TRUE}
lang_data %>%
   dplyr::mutate(
      language = forcats::as_factor(language),
      language = forcats::fct_reorder(
         .f = language,
         .x = prop_repos
      )
   ) %>%
   plotly::plot_ly() %>%
   plotly::add_trace(
      x = ~prop_repos,
      y = ~language,
      type = "bar",
      color = ~language,
      colors = colors_vct,
      hovertemplate = ~base::paste0(
         base::paste0("<b>", language, "</b>"),
         "<br>",
         "<b>Share:</b> ",
         formattable::percent(
            x = prop_size,
            digits = 2L
         ),
         "<br>",
         base::paste0(
            "Used in ",
            repos,
            " of ",
            dplyr::n_distinct(languages[["repo_name"]], na.rm = TRUE),
            " repos (",
            formattable::percent(
               x = repos / dplyr::n_distinct(languages[["repo_name"]], na.rm = TRUE),
               digits = 2L
            ),
            ")"
         ),
         "<extra></extra>"
      )
   ) %>%
   plotly::layout(
      xaxis = base::list(
         title = NA,
         tickformat = "%"
      ),
      yaxis = base::list(
         title = NA
      ),
      paper_bgcolor = "#f5f5f5",
      plot_bgcolor = "#f5f5f5"
   ) %>%
   plotly::config(
      displayModeBar = FALSE
   )
```

Row
-----------------------------------------------------------------------

### Relationship between size and usage

```{r, eval=TRUE}
lang_data %>% 
   plotly::plot_ly() %>% 
   plotly::add_trace(
      x = ~prop_size,
      y = ~prop_repos,
      type = "scatter",
      mode = "markers",
      color = ~language,
      colors = colors_vct,
      hovertemplate = ~base::paste0(
         base::paste0("<b>", language, "</b>"),
         "<br>",
         "<b>Byte size:</b> ",
         formattable::percent(
            x = prop_size,
            digits = 2L
         ),
         "<br>",
         "<b>Repo usage:</b> ",
         formattable::percent(
            x = prop_repos,
            digits = 2L
         ),
         "<extra></extra>"
      )
   ) %>% 
   plotly::layout(
      xaxis = base::list(
         title = "<b>Byte size</b>",
         tickformat = "%"
      ),
      yaxis = base::list(
         title = "<b>Repo usage</b>",
         tickformat = "%"
      ),
      paper_bgcolor = "#f5f5f5",
      plot_bgcolor = "#f5f5f5"
   ) %>% 
   plotly::config(
      displayModeBar = FALSE
   )
```

